"""Curated GTFS feed presets.

A hand-picked list of well-known city/region feeds so users don't have to
hunt URLs. Vienna is verified (default feed). Everything else is a
best-effort community URL: agencies move files around, so each preset
carries a ``verified`` flag + ``notes`` and the Sources page surfaces them
honestly instead of pretending every link is live.
"""

from __future__ import annotations

PRESETS: list[dict] = [
    # --- Austria (home turf) ---
    {
        "id": "vienna",
        "city": "Vienna",
        "country": "Austria",
        "region": "Austria",
        "agency": "Wiener Linien",
        "url": "https://www.wienerlinien.at/ogd_realtime/doku/ogd/gtfs/gtfs.zip",
        "timezone": "Europe/Vienna",
        "language": "de",
        "license_url": "https://www.wienerlinien.at/web/wl-en/open-data/agb",
        "verified": True,
        "needs_key": False,
        "notes": "Default feed. Verified working; ~4.6k stops, 6.1M stop times.",
    },
    {
        "id": "linz",
        "city": "Linz",
        "country": "Austria",
        "region": "Austria",
        "agency": "LINZ AG / OOEVV",
        "url": "https://www.linzag.at/static/content/files/GTFS.zip",
        "timezone": "Europe/Vienna",
        "language": "de",
        "license_url": "https://www.linzag.at/",
        "verified": False,
        "needs_key": False,
        "notes": "Community URL - verify before use. Check MobilityData catalog if stale.",
    },
    {
        "id": "graz",
        "city": "Graz",
        "country": "Austria",
        "region": "Austria",
        "agency": "Holding Graz / Verbund Linie",
        "url": "https://www.holding-graz.at/gtfs/gtfs.zip",
        "timezone": "Europe/Vienna",
        "language": "de",
        "license_url": "https://www.holding-graz.at/",
        "verified": False,
        "needs_key": False,
        "notes": "Community URL - verify before use.",
    },
    {
        "id": "salzburg",
        "city": "Salzburg",
        "country": "Austria",
        "region": "Austria",
        "agency": "Salzburger Verkehrsverbund",
        "url": "https://www.salzburg-verkehr.at/gtfs/gtfs.zip",
        "timezone": "Europe/Vienna",
        "language": "de",
        "license_url": "https://www.salzburg-verkehr.at/",
        "verified": False,
        "needs_key": False,
        "notes": "No direct city GTFS zip found (checked 2026-09-23, this link 404s). For rail via Salzburg Hbf use the oebb-austria preset (manual ToS download). City buses/O-Bus are Salzburg AG - check their site or data.gv.at if this goes stale.",
    },
    {
        "id": "oebb-austria",
        "city": "Austria-wide (rail)",
        "country": "Austria",
        "region": "Austria",
        "agency": "OEBB-Personenverkehr AG",
        "url": "https://data.oebb.at/de/datensaetze~soll-fahrplan-gtfs~",
        "timezone": "Europe/Vienna",
        "language": "de",
        "license_url": "https://data.oebb.at/de/nutzungsbedingungen",
        "verified": False,
        "needs_key": False,
        "notes": "Dataset page verified 2026-09-23: GTFS Soll-Fahrplan 2025/2026, CC-BY-4.0, covers OEBB + CAT + Montafonerbahn. No direct zip - accept ToS on the page, download manually, then add the file. Covers Salzburg/Innsbruck/Graz rail, not city buses.",
    },
    # --- Germany ---
    {
        "id": "munich",
        "city": "Munich",
        "country": "Germany",
        "region": "Germany",
        "agency": "MVV area via DELFI Germany feed (gtfs.de)",
        "url": "https://download.gtfs.de/germany/nv_free/latest.zip",
        "timezone": "Europe/Berlin",
        "language": "de",
        "license_url": "https://gtfs.de/en/feeds/de_nv/",
        "verified": True,
        "needs_key": False,
        "notes": "Verified 2026-09-23 (HTTP 200, ~269 MB zip). Germany-wide local-transit feed built from DELFI NeTEx data, CC-BY-4.0, refreshed 2026-09-19. Covers Munich/MVV plus every German city - filter stops after parsing. MVV publishes no stable direct GTFS URL (old fileadmin link 404s).",
    },
    {
        "id": "berlin",
        "city": "Berlin",
        "country": "Germany",
        "region": "Germany",
        "agency": "VBB area via DELFI Germany feed (gtfs.de)",
        "url": "https://download.gtfs.de/germany/nv_free/latest.zip",
        "timezone": "Europe/Berlin",
        "language": "de",
        "license_url": "https://gtfs.de/en/feeds/de_nv/",
        "verified": True,
        "needs_key": False,
        "notes": "Verified 2026-09-23 (HTTP 200, ~269 MB zip). Same Germany-wide DELFI feed as Munich - covers Berlin/VBB. VBB's own fileadmin path goes stale yearly, this one is refreshed regularly.",
    },
    {
        "id": "hamburg",
        "city": "Hamburg",
        "country": "Germany",
        "region": "Germany",
        "agency": "HVV area via DELFI Germany feed (gtfs.de)",
        "url": "https://download.gtfs.de/germany/nv_free/latest.zip",
        "timezone": "Europe/Berlin",
        "language": "de",
        "license_url": "https://gtfs.de/en/feeds/de_nv/",
        "verified": True,
        "needs_key": False,
        "notes": "Verified 2026-09-23 (HTTP 200, ~269 MB zip). Same Germany-wide DELFI feed - covers Hamburg/HVV local transit.",
    },
    {
        "id": "cologne",
        "city": "Cologne",
        "country": "Germany",
        "region": "Germany",
        "agency": "VRS area via DELFI Germany feed (gtfs.de)",
        "url": "https://download.gtfs.de/germany/nv_free/latest.zip",
        "timezone": "Europe/Berlin",
        "language": "de",
        "license_url": "https://gtfs.de/en/feeds/de_nv/",
        "verified": True,
        "needs_key": False,
        "notes": "Verified 2026-09-23 (HTTP 200, ~269 MB zip). Same Germany-wide DELFI feed - covers Cologne/VRS local transit.",
    },
    # --- Switzerland / West Europe ---
    {
        "id": "zurich",
        "city": "Zurich",
        "country": "Switzerland",
        "region": "DACH+CH",
        "agency": "ZVV / VBZ",
        "url": "https://data.stadt-zuerich.ch/dataset/vbz_fahrplan_gtfs/download/gtfs.zip",
        "timezone": "Europe/Zurich",
        "language": "de",
        "license_url": "https://data.stadt-zuerich.ch/",
        "verified": False,
        "needs_key": False,
        "notes": "Zurich open-data portal. SBB nationwide feed is larger - search MobilityData for 'SBB'.",
    },
    {
        "id": "paris",
        "city": "Paris",
        "country": "France",
        "region": "Western Europe",
        "agency": "IDFM (Ile-de-France Mobilites)",
        "url": "https://eu.ftp.opendatasoft.com/stif/GTFS/IDFM-gtfs.zip",
        "timezone": "Europe/Paris",
        "language": "fr",
        "license_url": "https://www.iledefrance-mobilites.fr/open-data",
        "verified": True,
        "needs_key": False,
        "notes": "Verified 2026-09-23 (HTTP 200, ~132 MB zip). Whole Ile-de-France - expect a long parse, watch the progress bar.",
    },
    {
        "id": "london",
        "city": "London",
        "country": "United Kingdom",
        "region": "Western Europe",
        "agency": "Transport for London (via third-party GTFS mirror)",
        "url": "https://storage.googleapis.com/storage/v1/b/mdbdatastore/o/mdb-latest-archive.zip?alt=media",
        "timezone": "Europe/London",
        "language": "en",
        "license_url": "https://tfl.gov.uk/corporate/terms-and-conditions/transport-data-service",
        "verified": False,
        "needs_key": False,
        "notes": "TfL publishes no official GTFS (they use TransXChange). This is a community mirror - prefer the MobilityData catalog entry for London.",
    },
    {
        "id": "amsterdam",
        "city": "Amsterdam",
        "country": "Netherlands",
        "region": "Western Europe",
        "agency": "GVB / NS",
        "url": "https://gtfs.ovapi.nl/nl/gtfs-nl.zip",
        "timezone": "Europe/Amsterdam",
        "language": "nl",
        "license_url": "https://gtfs.ovapi.nl/",
        "verified": False,
        "needs_key": False,
        "notes": "Netherlands-wide OVAPI snapshot. Big file - good stress test for the parser.",
    },
    # --- North America ---
    {
        "id": "new-york",
        "city": "New York",
        "country": "United States",
        "region": "North America",
        "agency": "MTA New York City Transit (subway)",
        "url": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct/gtfs.zip",
        "timezone": "America/New_York",
        "language": "en",
        "license_url": "https://new.mta.info/developers",
        "verified": False,
        "needs_key": False,
        "notes": "Static schedule only - realtime needs the GTFS-RT endpoints + API key. Direct fetch is bot-blocked (HTTP 403 on 2026-09-23) - download the zip in a browser, then add it manually.",
    },
    {
        "id": "boston",
        "city": "Boston",
        "country": "United States",
        "region": "North America",
        "agency": "MBTA",
        "url": "https://cdn.mbta.com/MBTA_GTFS.zip",
        "timezone": "America/New_York",
        "language": "en",
        "license_url": "https://www.mbta.com/developers/gtfs",
        "verified": False,
        "needs_key": False,
        "notes": "MBTA feed is clean and well-formed - good second feed after Vienna.",
    },
    {
        "id": "chicago",
        "city": "Chicago",
        "country": "United States",
        "region": "North America",
        "agency": "CTA",
        "url": "https://www.transitchicago.com/downloads/sch_data/google_transit.zip",
        "timezone": "America/Chicago",
        "language": "en",
        "license_url": "https://www.transitchicago.com/developers/gtfs",
        "verified": False,
        "needs_key": False,
        "notes": "CTA schedule feed. Stable URL for years.",
    },
    {
        "id": "portland",
        "city": "Portland",
        "country": "United States",
        "region": "North America",
        "agency": "TriMet (birthplace of GTFS)",
        "url": "https://trimet.org/transweb/transitcenter/GTFS-Feed/GTFS.zip",
        "timezone": "America/Los_Angeles",
        "language": "en",
        "license_url": "https://trimet.org/developers/",
        "verified": False,
        "needs_key": False,
        "notes": "Where GTFS was invented with Google in 2005. Historically stable URL.",
    },
    {
        "id": "san-francisco",
        "city": "San Francisco",
        "country": "United States",
        "region": "North America",
        "agency": "BART",
        "url": "https://www.bart.gov/dev/schedules/bart.zip",
        "timezone": "America/Los_Angeles",
        "language": "en",
        "license_url": "https://www.bart.gov/schedules/developers/gtfs",
        "verified": False,
        "needs_key": False,
        "notes": "Rail-only feed, small and fast to parse - good for testing.",
    },
    {
        "id": "toronto",
        "city": "Toronto",
        "country": "Canada",
        "region": "North America",
        "agency": "TTC",
        "url": "https://www.ttc.ca/ttc-routes-and-schedules/ttc-gtfs-data-files",
        "timezone": "America/Toronto",
        "language": "en",
        "license_url": "https://www.toronto.ca/city-government/data-research-maps/open-data/",
        "verified": False,
        "needs_key": False,
        "notes": "TTC hides the zip behind a landing page - download manually, then add via URL or file.",
    },
    # --- Asia (keys required) ---
    {
        "id": "tokyo",
        "city": "Tokyo",
        "country": "Japan",
        "region": "Asia",
        "agency": "Tokyo Metro (ODPT)",
        "url": "https://api.odpt.org/api/v4/gtfs/tokyometro/files/tokyometro_gtfs.zip",
        "timezone": "Asia/Tokyo",
        "language": "ja",
        "license_url": "https://developer-tokyometro.odpt.org/",
        "verified": False,
        "needs_key": True,
        "notes": "Requires a free ODPT API key - append ?acl:consumerKey=KEY or use the portal download.",
    },
    {
        "id": "singapore",
        "city": "Singapore",
        "country": "Singapore",
        "region": "Asia",
        "agency": "LTA DataMall",
        "url": "http://datamall2.mytransport.sg/ltaodataservice/GTFS.zip",
        "timezone": "Asia/Singapore",
        "language": "en",
        "license_url": "https://www.mytransport.sg/content/mytransport/home/dataMall.html",
        "verified": False,
        "needs_key": True,
        "notes": "Requires a free LTA DataMall API key (AccountKey header).",
    },
]

REGIONS = ["Austria", "Germany", "DACH+CH", "Western Europe", "North America", "Asia"]


def list_presets() -> list[dict]:
    """Return the full curated preset list (copies, safe to mutate)."""
    return [dict(p) for p in PRESETS]


def get_preset(preset_id: str) -> dict | None:
    """Look up one preset by id (case-insensitive)."""
    needle = (preset_id or "").strip().lower()
    for p in PRESETS:
        if p["id"].lower() == needle:
            return dict(p)
    return None
